/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/Analytics/dashboard": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Analytics/production-kpi": {
    get: {
      parameters: {
        query?: {
          fromDate?: string;
          toDate?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Analytics/wms-kpi": {
    get: {
      parameters: {
        query?: {
          fromDate?: string;
          toDate?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Analytics/guarantee-exposure": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Analytics/customs-summary": {
    get: {
      parameters: {
        query?: {
          fromDate?: string;
          toDate?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Analytics/inventory-by-location": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Analytics/mrn-usage": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Audit": {
    get: {
      parameters: {
        query?: {
          entityType?: string;
          entityId?: string;
          action?: string;
          from?: string;
          to?: string;
          take?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Auth/login": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
          "text/json": components["schemas"]["LoginRequest"];
          "application/*+json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["LoginResponse"];
            "application/json": components["schemas"]["LoginResponse"];
            "text/json": components["schemas"]["LoginResponse"];
          };
        };
      };
    };
  };
  "/api/Auth/refresh": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RefreshTokenRequest"];
          "text/json": components["schemas"]["RefreshTokenRequest"];
          "application/*+json": components["schemas"]["RefreshTokenRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["LoginResponse"];
            "application/json": components["schemas"]["LoginResponse"];
            "text/json": components["schemas"]["LoginResponse"];
          };
        };
      };
    };
  };
  "/api/Auth/logout": {
    post: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Auth/me": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["UserDto"];
            "application/json": components["schemas"]["UserDto"];
            "text/json": components["schemas"]["UserDto"];
          };
        };
      };
    };
  };
  "/api/MasterData/boms": {
    get: {
      parameters: {
        query?: {
          itemId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["BOMRequest"];
          "text/json": components["schemas"]["BOMRequest"];
          "application/*+json": components["schemas"]["BOMRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/boms/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["BOMRequest"];
          "text/json": components["schemas"]["BOMRequest"];
          "application/*+json": components["schemas"]["BOMRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/boms/item/{itemId}": {
    get: {
      parameters: {
        path: {
          itemId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/declarations": {
    get: {
      parameters: {
        query?: {
          isCleared?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateCustomsDeclarationCommand"];
          "text/json": components["schemas"]["CreateCustomsDeclarationCommand"];
          "application/*+json": components["schemas"]["CreateCustomsDeclarationCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/declarations/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateCustomsDeclarationCommand"];
          "text/json": components["schemas"]["UpdateCustomsDeclarationCommand"];
          "application/*+json": components["schemas"]["UpdateCustomsDeclarationCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/declarations/export": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateExportDeclarationCommand"];
          "text/json": components["schemas"]["CreateExportDeclarationCommand"];
          "application/*+json": components["schemas"]["CreateExportDeclarationCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/declarations/return": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateReturnDeclarationCommand"];
          "text/json": components["schemas"]["CreateReturnDeclarationCommand"];
          "application/*+json": components["schemas"]["CreateReturnDeclarationCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/declarations/waste": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateWasteDeclarationCommand"];
          "text/json": components["schemas"]["CreateWasteDeclarationCommand"];
          "application/*+json": components["schemas"]["CreateWasteDeclarationCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/declarations/{id}/certify": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CertifyDeclarationBody"];
          "text/json": components["schemas"]["CertifyDeclarationBody"];
          "application/*+json": components["schemas"]["CertifyDeclarationBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/pee/060": {
    get: {
      parameters: {
        query?: {
          authorizationId?: string;
          from?: string;
          to?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/declarations/validate": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateCustomsDeclarationCommand"];
          "text/json": components["schemas"]["CreateCustomsDeclarationCommand"];
          "application/*+json": components["schemas"]["CreateCustomsDeclarationCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/tariff-lookup/{tariffCode}": {
    get: {
      parameters: {
        path: {
          tariffCode: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/procedures": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/lon-authorizations": {
    get: {
      parameters: {
        query?: {
          activeOnly?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/mrn-registry": {
    get: {
      parameters: {
        query?: {
          mrn?: string;
          isActive?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Customs/mrn-registry/{mrn}": {
    get: {
      parameters: {
        path: {
          mrn: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Employees": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateEmployeeRequest"];
          "text/json": components["schemas"]["CreateEmployeeRequest"];
          "application/*+json": components["schemas"]["CreateEmployeeRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Employees/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateEmployeeRequest"];
          "text/json": components["schemas"]["UpdateEmployeeRequest"];
          "application/*+json": components["schemas"]["UpdateEmployeeRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/employees": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Guarantee/accounts": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["GuaranteeAccountRequest"];
          "text/json": components["schemas"]["GuaranteeAccountRequest"];
          "application/*+json": components["schemas"]["GuaranteeAccountRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Guarantee/accounts/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["GuaranteeAccountRequest"];
          "text/json": components["schemas"]["GuaranteeAccountRequest"];
          "application/*+json": components["schemas"]["GuaranteeAccountRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Guarantee/debit": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["DebitGuaranteeCommand"];
          "text/json": components["schemas"]["DebitGuaranteeCommand"];
          "application/*+json": components["schemas"]["DebitGuaranteeCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Guarantee/credit": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreditGuaranteeCommand"];
          "text/json": components["schemas"]["CreditGuaranteeCommand"];
          "application/*+json": components["schemas"]["CreditGuaranteeCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Guarantee/ledger": {
    get: {
      parameters: {
        query?: {
          accountId?: string;
          isReleased?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["GuaranteeLedgerRequest"];
          "text/json": components["schemas"]["GuaranteeLedgerRequest"];
          "application/*+json": components["schemas"]["GuaranteeLedgerRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Guarantee/accounts/traffic-light": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Guarantee/active-guarantees": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Guarantee/ledger/{id}/release": {
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Hr/attendance/clock-in": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ClockBody"];
          "text/json": components["schemas"]["ClockBody"];
          "application/*+json": components["schemas"]["ClockBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Hr/attendance/clock-out": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ClockBody"];
          "text/json": components["schemas"]["ClockBody"];
          "application/*+json": components["schemas"]["ClockBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Hr/attendance/today": {
    get: {
      parameters: {
        query?: {
          day?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Hr/attendance": {
    get: {
      parameters: {
        query?: {
          employeeId?: string;
          from?: string;
          to?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Hr/absences": {
    get: {
      parameters: {
        query?: {
          employeeId?: string;
          pendingOnly?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateAbsenceBody"];
          "text/json": components["schemas"]["CreateAbsenceBody"];
          "application/*+json": components["schemas"]["CreateAbsenceBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Hr/absences/{id}/decide": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["DecideAbsenceBody"];
          "text/json": components["schemas"]["DecideAbsenceBody"];
          "application/*+json": components["schemas"]["DecideAbsenceBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Hr/assignments": {
    get: {
      parameters: {
        query?: {
          employeeId?: string;
          machineId?: string;
          activeOnly?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateAssignmentBody"];
          "text/json": components["schemas"]["CreateAssignmentBody"];
          "application/*+json": components["schemas"]["CreateAssignmentBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Hr/assignments/{id}/end": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["EndAssignmentBody"];
          "text/json": components["schemas"]["EndAssignmentBody"];
          "application/*+json": components["schemas"]["EndAssignmentBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/sessions": {
    get: {
      parameters: {
        query?: {
          take?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      parameters: {
        query?: {
          targetEntity?: string;
          partnerContextId?: string;
        };
      };
      requestBody?: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            file?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/presets/kw12": {
    post: {
      requestBody?: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            file?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/sessions/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/sessions/{id}/mapping": {
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ApplyMappingRequest"];
          "text/json": components["schemas"]["ApplyMappingRequest"];
          "application/*+json": components["schemas"]["ApplyMappingRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/mapping-profiles": {
    get: {
      parameters: {
        query?: {
          targetEntity?: string;
          partnerContextId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/mapping-profiles/{id}": {
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/sessions/{id}/defaults": {
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SetDefaultsRequest"];
          "text/json": components["schemas"]["SetDefaultsRequest"];
          "application/*+json": components["schemas"]["SetDefaultsRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/sessions/{id}/transforms": {
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SetTransformsRequest"];
          "text/json": components["schemas"]["SetTransformsRequest"];
          "application/*+json": components["schemas"]["SetTransformsRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/sessions/{id}/preview-transformed": {
    get: {
      parameters: {
        query?: {
          take?: number;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/sessions/{id}/dry-run": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/sessions/{id}/commit": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/targets": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/import/targets/{name}": {
    get: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/items": {
    get: {
      parameters: {
        query?: {
          search?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ItemRequest"];
          "text/json": components["schemas"]["ItemRequest"];
          "application/*+json": components["schemas"]["ItemRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/items/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ItemRequest"];
          "text/json": components["schemas"]["ItemRequest"];
          "application/*+json": components["schemas"]["ItemRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/items/backfill-base-variants": {
    post: {
      parameters: {
        query?: {
          dryRun?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/items/{id}/import-attributes": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/items/article-picker": {
    get: {
      parameters: {
        query?: {
          query?: string;
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/KnowledgeBase/ask": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["QuestionRequest"];
          "text/json": components["schemas"]["QuestionRequest"];
          "application/*+json": components["schemas"]["QuestionRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["RAGResponse"];
            "application/json": components["schemas"]["RAGResponse"];
            "text/json": components["schemas"]["RAGResponse"];
          };
        };
      };
    };
  };
  "/api/KnowledgeBase/explain": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ConceptRequest"];
          "text/json": components["schemas"]["ConceptRequest"];
          "application/*+json": components["schemas"]["ConceptRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["RAGResponse"];
            "application/json": components["schemas"]["RAGResponse"];
            "text/json": components["schemas"]["RAGResponse"];
          };
        };
      };
    };
  };
  "/api/KnowledgeBase/search": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SearchRequest"];
          "text/json": components["schemas"]["SearchRequest"];
          "application/*+json": components["schemas"]["SearchRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["SearchResult"][];
            "application/json": components["schemas"]["SearchResult"][];
            "text/json": components["schemas"]["SearchResult"][];
          };
        };
      };
    };
  };
  "/api/KnowledgeBase/health": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/KnowledgeBase/stats": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/KnowledgeBase/tariff-codes": {
    get: {
      parameters: {
        query?: {
          search?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/KnowledgeBase/regulations": {
    get: {
      parameters: {
        query?: {
          search?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/KnowledgeBase/code-lists": {
    get: {
      parameters: {
        query?: {
          listType?: string;
          search?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/KnowledgeBase/validation-rules": {
    get: {
      parameters: {
        query?: {
          fieldName?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/KnowledgeBase/code-lists/items": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CodeListItemRequest"];
          "text/json": components["schemas"]["CodeListItemRequest"];
          "application/*+json": components["schemas"]["CodeListItemRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/KnowledgeBase/code-lists/items/{id}": {
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CodeListItemRequest"];
          "text/json": components["schemas"]["CodeListItemRequest"];
          "application/*+json": components["schemas"]["CodeListItemRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/locations": {
    get: {
      parameters: {
        query?: {
          warehouseId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["LocationRequest"];
          "text/json": components["schemas"]["LocationRequest"];
          "application/*+json": components["schemas"]["LocationRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/locations/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["LocationRequest"];
          "text/json": components["schemas"]["LocationRequest"];
          "application/*+json": components["schemas"]["LocationRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Machines/{id}/state-events": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["LogStateBody"];
          "text/json": components["schemas"]["LogStateBody"];
          "application/*+json": components["schemas"]["LogStateBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Machines/current-states": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Machines/downtime": {
    get: {
      parameters: {
        query?: {
          machineId?: string;
          from?: string;
          to?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["LogDowntimeBody"];
          "text/json": components["schemas"]["LogDowntimeBody"];
          "application/*+json": components["schemas"]["LogDowntimeBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Machines/downtime/{id}/close": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CloseDowntimeBody"];
          "text/json": components["schemas"]["CloseDowntimeBody"];
          "application/*+json": components["schemas"]["CloseDowntimeBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Machines/downtime/pareto": {
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Machines/maintenance-schedules": {
    get: {
      parameters: {
        query?: {
          activeOnly?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateScheduleBody"];
          "text/json": components["schemas"]["CreateScheduleBody"];
          "application/*+json": components["schemas"]["CreateScheduleBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Machines/maintenance-schedules/{id}": {
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateScheduleBody"];
          "text/json": components["schemas"]["UpdateScheduleBody"];
          "application/*+json": components["schemas"]["UpdateScheduleBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Machines/maintenance-work-orders": {
    get: {
      parameters: {
        query?: {
          machineId?: string;
          openOnly?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateWorkOrderBody"];
          "text/json": components["schemas"]["CreateWorkOrderBody"];
          "application/*+json": components["schemas"]["CreateWorkOrderBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Machines/maintenance-work-orders/{id}/complete": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CompleteWorkOrderBody"];
          "text/json": components["schemas"]["CompleteWorkOrderBody"];
          "application/*+json": components["schemas"]["CompleteWorkOrderBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/machines": {
    get: {
      parameters: {
        query?: {
          workCenterId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MachineRequest"];
          "text/json": components["schemas"]["MachineRequest"];
          "application/*+json": components["schemas"]["MachineRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/machines/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MachineRequest"];
          "text/json": components["schemas"]["MachineRequest"];
          "application/*+json": components["schemas"]["MachineRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/partners": {
    get: {
      parameters: {
        query?: {
          type?: components["schemas"]["PartnerType"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PartnerRequest"];
          "text/json": components["schemas"]["PartnerRequest"];
          "application/*+json": components["schemas"]["PartnerRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/partners/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PartnerRequest"];
          "text/json": components["schemas"]["PartnerRequest"];
          "application/*+json": components["schemas"]["PartnerRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Permissions": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Production/orders": {
    get: {
      parameters: {
        query?: {
          status?: components["schemas"]["ProductionOrderStatus"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateProductionOrderCommand"];
          "text/json": components["schemas"]["CreateProductionOrderCommand"];
          "application/*+json": components["schemas"]["CreateProductionOrderCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Production/orders/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Production/orders/{id}/issues": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateMaterialIssueCommand"];
          "text/json": components["schemas"]["CreateMaterialIssueCommand"];
          "application/*+json": components["schemas"]["CreateMaterialIssueCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Production/orders/{id}/release": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Production/orders/{id}/issues/bulk": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["IssueAllMaterialsBody"];
          "text/json": components["schemas"]["IssueAllMaterialsBody"];
          "application/*+json": components["schemas"]["IssueAllMaterialsBody"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Production/orders/{id}/material-issues": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Production/orders/{id}/receipts": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateProductionReceiptCommand"];
          "text/json": components["schemas"]["CreateProductionReceiptCommand"];
          "application/*+json": components["schemas"]["CreateProductionReceiptCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Production/shortage": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Production/boms": {
    get: {
      parameters: {
        query?: {
          itemId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/health/live": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/health/ready": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/health/live": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/health/ready": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/health": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/health/db": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/QuickEntry/execute": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["QuickEntryRequest"];
          "text/json": components["schemas"]["QuickEntryRequest"];
          "application/*+json": components["schemas"]["QuickEntryRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Roles": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RoleRequest"];
          "text/json": components["schemas"]["RoleRequest"];
          "application/*+json": components["schemas"]["RoleRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Roles/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RoleRequest"];
          "text/json": components["schemas"]["RoleRequest"];
          "application/*+json": components["schemas"]["RoleRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/routings": {
    get: {
      parameters: {
        query?: {
          itemId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RoutingRequest"];
          "text/json": components["schemas"]["RoutingRequest"];
          "application/*+json": components["schemas"]["RoutingRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/routings/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RoutingRequest"];
          "text/json": components["schemas"]["RoutingRequest"];
          "application/*+json": components["schemas"]["RoutingRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/routings/item/{itemId}": {
    get: {
      parameters: {
        path: {
          itemId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Shifts": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateShiftRequest"];
          "text/json": components["schemas"]["CreateShiftRequest"];
          "application/*+json": components["schemas"]["CreateShiftRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Shifts/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateShiftRequest"];
          "text/json": components["schemas"]["UpdateShiftRequest"];
          "application/*+json": components["schemas"]["UpdateShiftRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Tenants": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["Tenant"][];
            "application/json": components["schemas"]["Tenant"][];
            "text/json": components["schemas"]["Tenant"][];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["TenantRequest"];
          "text/json": components["schemas"]["TenantRequest"];
          "application/*+json": components["schemas"]["TenantRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["Tenant"];
            "application/json": components["schemas"]["Tenant"];
            "text/json": components["schemas"]["Tenant"];
          };
        };
      };
    };
  };
  "/api/Tenants/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["Tenant"];
            "application/json": components["schemas"]["Tenant"];
            "text/json": components["schemas"]["Tenant"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["TenantRequest"];
          "text/json": components["schemas"]["TenantRequest"];
          "application/*+json": components["schemas"]["TenantRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["Tenant"];
            "application/json": components["schemas"]["Tenant"];
            "text/json": components["schemas"]["Tenant"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Tenants/{id}/settings/fefo": {
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["TenantFefoFlagRequest"];
          "text/json": components["schemas"]["TenantFefoFlagRequest"];
          "application/*+json": components["schemas"]["TenantFefoFlagRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": components["schemas"]["Tenant"];
            "application/json": components["schemas"]["Tenant"];
            "text/json": components["schemas"]["Tenant"];
          };
        };
      };
    };
  };
  "/api/Traceability/trace-forward": {
    get: {
      parameters: {
        query?: {
          batchNumber?: string;
          mrn?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Traceability/trace-backward": {
    get: {
      parameters: {
        query?: {
          batchNumber?: string;
          mrn?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Traceability/genealogy/{batchNumber}": {
    get: {
      parameters: {
        path: {
          batchNumber: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Traceability/trace-full": {
    get: {
      parameters: {
        query?: {
          batchNumber?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/uom": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UoMRequest"];
          "text/json": components["schemas"]["UoMRequest"];
          "application/*+json": components["schemas"]["UoMRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/uom/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UoMRequest"];
          "text/json": components["schemas"]["UoMRequest"];
          "application/*+json": components["schemas"]["UoMRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/UserPrefs/field-history": {
    get: {
      parameters: {
        query?: {
          fieldKey?: string;
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RecordFieldValueRequest"];
          "text/json": components["schemas"]["RecordFieldValueRequest"];
          "application/*+json": components["schemas"]["RecordFieldValueRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Users": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateUserRequest"];
          "text/json": components["schemas"]["CreateUserRequest"];
          "application/*+json": components["schemas"]["CreateUserRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Users/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateUserRequest"];
          "text/json": components["schemas"]["UpdateUserRequest"];
          "application/*+json": components["schemas"]["UpdateUserRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/Users/{id}/change-password": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ChangePasswordRequest"];
          "text/json": components["schemas"]["ChangePasswordRequest"];
          "application/*+json": components["schemas"]["ChangePasswordRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/warehouses": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["WarehouseRequest"];
          "text/json": components["schemas"]["WarehouseRequest"];
          "application/*+json": components["schemas"]["WarehouseRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/warehouses/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["WarehouseRequest"];
          "text/json": components["schemas"]["WarehouseRequest"];
          "application/*+json": components["schemas"]["WarehouseRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/receipts": {
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateReceiptCommand"];
          "text/json": components["schemas"]["CreateReceiptCommand"];
          "application/*+json": components["schemas"]["CreateReceiptCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/receipts/bulk-from-declaration": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["BulkReceiptFromDeclarationCommand"];
          "text/json": components["schemas"]["BulkReceiptFromDeclarationCommand"];
          "application/*+json": components["schemas"]["BulkReceiptFromDeclarationCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/receipts/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/inventory": {
    get: {
      parameters: {
        query?: {
          itemId?: string;
          locationId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/inventory/mozni-minusi": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/inventory/move-batch": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MoveBatchAcrossStagesCommand"];
          "text/json": components["schemas"]["MoveBatchAcrossStagesCommand"];
          "application/*+json": components["schemas"]["MoveBatchAcrossStagesCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/inventory/mass-transfer/preview": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MassLocationTransferPreviewQuery"];
          "text/json": components["schemas"]["MassLocationTransferPreviewQuery"];
          "application/*+json": components["schemas"]["MassLocationTransferPreviewQuery"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/inventory/mass-transfer": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MassLocationTransferCommand"];
          "text/json": components["schemas"]["MassLocationTransferCommand"];
          "application/*+json": components["schemas"]["MassLocationTransferCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/shipments": {
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateShipmentRequest"];
          "text/json": components["schemas"]["CreateShipmentRequest"];
          "application/*+json": components["schemas"]["CreateShipmentRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/shipments/bulk-from-fg": {
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["BulkShipmentFromFGCommand"];
          "text/json": components["schemas"]["BulkShipmentFromFGCommand"];
          "application/*+json": components["schemas"]["BulkShipmentFromFGCommand"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/transfers": {
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateTransferRequest"];
          "text/json": components["schemas"]["CreateTransferRequest"];
          "application/*+json": components["schemas"]["CreateTransferRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/cycle-counts": {
    get: {
      parameters: {
        query?: {
          status?: components["schemas"]["CycleCountStatus"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateCycleCountRequest"];
          "text/json": components["schemas"]["CreateCycleCountRequest"];
          "application/*+json": components["schemas"]["CreateCycleCountRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/WMS/pick-tasks": {
    get: {
      parameters: {
        query?: {
          status?: components["schemas"]["PickTaskStatus"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/workcenters": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["WorkCenterRequest"];
          "text/json": components["schemas"]["WorkCenterRequest"];
          "application/*+json": components["schemas"]["WorkCenterRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/work-centers": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["WorkCenterRequest"];
          "text/json": components["schemas"]["WorkCenterRequest"];
          "application/*+json": components["schemas"]["WorkCenterRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/workcenters/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["WorkCenterRequest"];
          "text/json": components["schemas"]["WorkCenterRequest"];
          "application/*+json": components["schemas"]["WorkCenterRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/MasterData/work-centers/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["WorkCenterRequest"];
          "text/json": components["schemas"]["WorkCenterRequest"];
          "application/*+json": components["schemas"]["WorkCenterRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Format: int32
     * @enum {integer}
     */
    AbsenceType: 1 | 2 | 3 | 4 | 5 | 99;
    ApplyMappingRequest: {
      mapping?: components["schemas"]["ImportMapping"];
      targetEntity?: string | null;
      /** Format: uuid */
      partnerContextId?: string | null;
      saveAsProfileLabel?: string | null;
    };
    BOMLineRequest: {
      /** Format: uuid */
      componentItemId?: string;
      /** Format: double */
      quantity?: number;
      /** Format: uuid */
      uoMId?: string;
      /** Format: double */
      scrapFactor?: number;
      /** Format: int32 */
      sequenceNumber?: number;
    };
    BOMRequest: {
      /** Format: uuid */
      itemId?: string;
      version?: string | null;
      /** Format: double */
      quantity?: number;
      /** Format: uuid */
      uoMId?: string;
      /** Format: date-time */
      validFrom?: string | null;
      /** Format: date-time */
      validTo?: string | null;
      notes?: string | null;
      isActive?: boolean;
      lines?: components["schemas"]["BOMLineRequest"][] | null;
    };
    BulkReceiptFromDeclarationCommand: {
      /** Format: uuid */
      customsDeclarationId?: string;
      /** Format: uuid */
      warehouseId?: string;
      /** Format: uuid */
      targetLocationId?: string | null;
      /** Format: date-time */
      receiptDate?: string | null;
      referenceNumber?: string | null;
    };
    BulkShipmentFromFGCommand: {
      /** Format: uuid */
      itemId?: string | null;
      batchNumber?: string | null;
      mrn?: string | null;
      /** Format: uuid */
      locationId?: string | null;
      /** Format: uuid */
      sourceWarehouseId?: string | null;
      /** Format: uuid */
      productionOrderId?: string | null;
      /** Format: uuid */
      partnerId?: string | null;
      /** Format: uuid */
      customsProcedureId?: string | null;
      declarationNumber?: string | null;
      /** Format: date-time */
      shipmentDate?: string | null;
      reference?: string | null;
      createExportDeclaration?: boolean;
    };
    CertifyDeclarationBody: {
      zaverkaNumber?: string | null;
      /** Format: date-time */
      zaverkaDate?: string;
    };
    ChangePasswordRequest: {
      currentPassword?: string | null;
      newPassword?: string | null;
    };
    ClockBody: {
      /** Format: uuid */
      employeeId?: string;
      /** Format: date-time */
      at?: string | null;
    };
    CloseDowntimeBody: {
      /** Format: date-time */
      end?: string;
    };
    CodeListItemRequest: {
      listType?: string | null;
      code?: string | null;
      descriptionMK?: string | null;
      descriptionEN?: string | null;
      /** Format: int32 */
      sortOrder?: number;
    };
    CompleteWorkOrderBody: {
      /** Format: date-time */
      completedAt?: string | null;
      notes?: string | null;
      /** Format: double */
      costImpact?: number | null;
    };
    ConceptRequest: {
      concept?: string | null;
    };
    CreateAbsenceBody: {
      /** Format: uuid */
      employeeId?: string;
      /** Format: date-time */
      from?: string;
      /** Format: date-time */
      to?: string;
      type?: components["schemas"]["AbsenceType"];
      reason?: string | null;
    };
    CreateAssignmentBody: {
      /** Format: uuid */
      employeeId?: string;
      /** Format: uuid */
      machineId?: string;
      /** Format: date-time */
      validFrom?: string;
      /** Format: date-time */
      validTo?: string | null;
      notes?: string | null;
    };
    CreateCustomsDeclarationCommand: {
      declarationNumber?: string | null;
      mrn?: string | null;
      /** Format: date-time */
      declarationDate?: string;
      /** Format: uuid */
      customsProcedureId?: string;
      /** Format: uuid */
      partnerId?: string | null;
      /** Format: uuid */
      lonAuthorizationId?: string | null;
      /** Format: double */
      totalCustomsValue?: number;
      currency?: string | null;
      /** Format: date-time */
      dueDate?: string | null;
      previousProcedureCode?: string | null;
      /** Format: double */
      landingCosts?: number | null;
      /** Format: double */
      discount?: number | null;
      senderName?: string | null;
      senderAddress?: string | null;
      senderCountry?: string | null;
      countryOfDispatch?: string | null;
      countryOfDestination?: string | null;
      specialRemarks?: string | null;
      status?: components["schemas"]["DeclarationStatus"];
      lines?: components["schemas"]["DeclarationLineDto"][] | null;
    };
    CreateCycleCountRequest: {
      /** Format: date-time */
      scheduledDate?: string;
      /** Format: uuid */
      warehouseId?: string;
      notes?: string | null;
    };
    CreateEmployeeRequest: {
      /** Format: uuid */
      userId?: string;
      firstName?: string | null;
      lastName?: string | null;
      email?: string | null;
      phone?: string | null;
      position?: string | null;
      department?: string | null;
      hireDate?: string | null;
    };
    CreateExportDeclarationCommand: {
      declarationNumber?: string | null;
      mrn?: string | null;
      /** Format: date-time */
      declarationDate?: string;
      /** Format: uuid */
      customsProcedureId?: string;
      /** Format: uuid */
      partnerId?: string | null;
      currency?: string | null;
      /** Format: double */
      totalCustomsValue?: number;
      senderName?: string | null;
      senderAddress?: string | null;
      senderCountry?: string | null;
      countryOfDispatch?: string | null;
      countryOfDestination?: string | null;
      specialRemarks?: string | null;
      lines?: components["schemas"]["ExportLineDto"][] | null;
    };
    CreateMaterialIssueCommand: {
      /** Format: uuid */
      productionOrderId?: string;
      /** Format: date-time */
      issueDate?: string;
      /** Format: uuid */
      issuedByEmployeeId?: string | null;
      lines?: components["schemas"]["MaterialIssueLineDto"][] | null;
    };
    CreateProductionOrderCommand: {
      /** Format: uuid */
      itemId?: string;
      /** Format: double */
      orderQuantity?: number;
      /** Format: uuid */
      uoMId?: string;
      /** Format: date-time */
      plannedStartDate?: string;
      /** Format: date-time */
      plannedEndDate?: string;
      /** Format: uuid */
      bomId?: string | null;
      /** Format: uuid */
      routingId?: string | null;
      salesOrderReference?: string | null;
      notes?: string | null;
      /** Format: uuid */
      partnerId?: string | null;
    };
    CreateProductionReceiptCommand: {
      /** Format: uuid */
      productionOrderId?: string;
      /** Format: date-time */
      receiptDate?: string;
      /** Format: uuid */
      itemId?: string;
      /** Format: double */
      quantity?: number;
      /** Format: double */
      scrapQuantity?: number | null;
      /** Format: uuid */
      uoMId?: string;
      /** Format: uuid */
      locationId?: string;
      batchNumber?: string | null;
      qualityStatus?: components["schemas"]["QualityStatus"];
      /** Format: uuid */
      receivedByEmployeeId?: string | null;
      materialConsumption?: components["schemas"]["MaterialConsumptionDto"][] | null;
    };
    CreateReceiptCommand: {
      /** Format: date-time */
      receiptDate?: string;
      /** Format: uuid */
      partnerId?: string | null;
      /** Format: uuid */
      warehouseId?: string;
      /** Format: uuid */
      locationId?: string | null;
      purchaseOrderNumber?: string | null;
      referenceNumber?: string | null;
      lines?: components["schemas"]["ReceiptLineDto"][] | null;
    };
    CreateReturnDeclarationCommand: {
      declarationNumber?: string | null;
      mrn?: string | null;
      /** Format: date-time */
      declarationDate?: string;
      /** Format: uuid */
      customsProcedureId?: string;
      /** Format: uuid */
      partnerId?: string | null;
      currency?: string | null;
      /** Format: double */
      totalCustomsValue?: number;
      senderName?: string | null;
      senderAddress?: string | null;
      senderCountry?: string | null;
      countryOfDispatch?: string | null;
      countryOfDestination?: string | null;
      specialRemarks?: string | null;
      lines?: components["schemas"]["ReturnLineDto"][] | null;
    };
    CreateScheduleBody: {
      /** Format: uuid */
      machineId?: string;
      taskDescription?: string | null;
      /** Format: int32 */
      intervalDays?: number;
      /** Format: date-time */
      lastDone?: string | null;
      /** Format: date-time */
      nextDue?: string | null;
    };
    CreateShiftRequest: {
      name?: string | null;
      startTime?: string | null;
      endTime?: string | null;
      description?: string | null;
    };
    CreateShipmentRequest: {
      /** Format: uuid */
      customerId?: string | null;
      /** Format: uuid */
      carrierId?: string | null;
      trackingNumber?: string | null;
      salesOrderNumber?: string | null;
    };
    CreateTransferRequest: {
      /** Format: uuid */
      fromLocationId?: string;
      /** Format: uuid */
      toLocationId?: string;
      notes?: string | null;
    };
    CreateUserRequest: {
      username?: string | null;
      email?: string | null;
      fullName?: string | null;
      password?: string | null;
      roleIds?: string[] | null;
      /** Format: uuid */
      tenantId?: string | null;
    };
    CreateWasteDeclarationCommand: {
      /** Format: date-time */
      wasteDate?: string;
      mrn?: string | null;
      /** Format: double */
      quantity?: number;
      reason?: string | null;
      /** Format: uuid */
      itemId?: string | null;
      batchNumber?: string | null;
      /** Format: uuid */
      locationId?: string | null;
      slots?: components["schemas"]["WasteSlot"][] | null;
    };
    CreateWorkOrderBody: {
      /** Format: uuid */
      machineId?: string;
      /** Format: uuid */
      scheduleId?: string | null;
      /** Format: date-time */
      scheduledDate?: string;
      /** Format: uuid */
      technicianEmployeeId?: string | null;
      taskDescription?: string | null;
      notes?: string | null;
      /** Format: double */
      costImpact?: number | null;
    };
    CreditGuaranteeCommand: {
      /** Format: uuid */
      guaranteeAccountId?: string;
      /** Format: double */
      amount?: number;
      description?: string | null;
      mrn?: string | null;
      /** Format: uuid */
      customsDeclarationId?: string | null;
      /** Format: uuid */
      relatedDebitEntryId?: string | null;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    CycleCountStatus: 1 | 2 | 3 | 4;
    DebitGuaranteeCommand: {
      /** Format: uuid */
      guaranteeAccountId?: string;
      /** Format: double */
      amount?: number;
      description?: string | null;
      mrn?: string | null;
      /** Format: uuid */
      customsDeclarationId?: string | null;
      /** Format: date-time */
      expectedReleaseDate?: string | null;
    };
    DecideAbsenceBody: {
      approve?: boolean;
    };
    DeclarationLineDto: {
      /** Format: uuid */
      itemId?: string;
      tariffCode?: string | null;
      /** Format: double */
      quantity?: number;
      /** Format: uuid */
      uoMId?: string;
      /** Format: double */
      customsValue?: number;
      countryOfOrigin?: string | null;
      /** Format: double */
      dutyRate?: number;
      /** Format: double */
      vatRate?: number;
      locationOfGoods?: string | null;
      /** Format: double */
      grossWeight?: number | null;
      /** Format: double */
      netWeight?: number | null;
      /** Format: double */
      additionalUnit?: number | null;
      calculationMethod?: string | null;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    DeclarationStatus: 0 | 1 | 2 | 3 | 99;
    /**
     * Format: int32
     * @enum {integer}
     */
    DowntimeCategory: 1 | 2 | 3 | 4 | 5 | 6 | 99;
    EmployeeDto: {
      /** Format: uuid */
      id?: string;
      employeeNumber?: string | null;
      firstName?: string | null;
      lastName?: string | null;
      email?: string | null;
      phone?: string | null;
      department?: string | null;
      position?: string | null;
      /** Format: date-time */
      hireDate?: string | null;
      shift?: components["schemas"]["ShiftDto"];
      isActive?: boolean;
    };
    EndAssignmentBody: {
      /** Format: date-time */
      validTo?: string;
    };
    ExportLineDto: {
      /** Format: uuid */
      itemId?: string;
      tariffCode?: string | null;
      /** Format: double */
      quantity?: number;
      /** Format: uuid */
      uoMId?: string;
      /** Format: double */
      customsValue?: number;
      countryOfOrigin?: string | null;
      /** Format: double */
      netWeight?: number | null;
      /** Format: double */
      grossWeight?: number | null;
      calculationMethod?: string | null;
      batchNumber?: string | null;
      /** Format: uuid */
      locationId?: string | null;
      sourceMRN?: string | null;
      /** Format: double */
      dischargeQuantity?: number;
    };
    GuaranteeAccountRequest: {
      accountNumber?: string | null;
      accountName?: string | null;
      /** Format: uuid */
      bankPartnerId?: string;
      currency?: string | null;
      /** Format: double */
      totalLimit?: number;
      isActive?: boolean;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    GuaranteeEntryType: 1 | 2;
    GuaranteeLedgerRequest: {
      /** Format: uuid */
      guaranteeAccountId?: string;
      entryType?: components["schemas"]["GuaranteeEntryType"];
      /** Format: double */
      amount?: number;
      currency?: string | null;
      mrn?: string | null;
      /** Format: uuid */
      customsDeclarationId?: string | null;
      description?: string | null;
      /** Format: date-time */
      expectedReleaseDate?: string | null;
    };
    IDomainEvent: {
      /** Format: date-time */
      occurredOn?: string;
      /** Format: uuid */
      eventId?: string;
    };
    ImportColumnTransform: {
      sourceHeader?: string | null;
      rules?: string[] | null;
    };
    ImportDefaults: {
      values?: ({
        [key: string]: string | null;
      }) | null;
    };
    ImportMapping: {
      columns?: components["schemas"]["ImportMappingColumn"][] | null;
    };
    ImportMappingColumn: {
      sourceHeader?: string | null;
      targetField?: string | null;
      ignore?: boolean;
    };
    ImportTransforms: {
      columns?: components["schemas"]["ImportColumnTransform"][] | null;
    };
    IssueAllMaterialsBody: {
      /** Format: date-time */
      issueDate?: string;
      /** Format: uuid */
      issuedByEmployeeId?: string | null;
    };
    ItemRequest: {
      code?: string | null;
      name?: string | null;
      description?: string | null;
      itemType?: components["schemas"]["ItemType"];
      /** Format: uuid */
      uoMId?: string;
      isBatchRequired?: boolean;
      isMRNRequired?: boolean;
      countryOfOrigin?: string | null;
      hsCode?: string | null;
      isActive?: boolean;
      /** Format: double */
      standardCost?: number | null;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    ItemType: 1 | 2 | 3 | 4;
    LocationRequest: {
      /** Format: uuid */
      warehouseId?: string;
      code?: string | null;
      name?: string | null;
      locationType?: components["schemas"]["LocationType"];
      /** Format: uuid */
      parentLocationId?: string | null;
      aisle?: string | null;
      rack?: string | null;
      shelf?: string | null;
      bin?: string | null;
      /** Format: double */
      maxCapacity?: number | null;
      isActive?: boolean;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    LocationType: 1 | 2 | 3 | 4 | 5 | 6 | 7;
    LogDowntimeBody: {
      /** Format: uuid */
      machineId?: string;
      /** Format: date-time */
      start?: string;
      /** Format: date-time */
      end?: string | null;
      category?: components["schemas"]["DowntimeCategory"];
      reason?: string | null;
      /** Format: double */
      costImpact?: number | null;
      /** Format: uuid */
      reportedByEmployeeId?: string | null;
    };
    LogStateBody: {
      state?: components["schemas"]["MachineState"];
      /** Format: date-time */
      changedAt?: string | null;
      /** Format: uuid */
      changedByEmployeeId?: string | null;
      notes?: string | null;
    };
    LoginRequest: {
      username?: string | null;
      password?: string | null;
    };
    LoginResponse: {
      accessToken?: string | null;
      refreshToken?: string | null;
      /** Format: date-time */
      expiresAt?: string;
      user?: components["schemas"]["UserDto"];
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    LonProcessState: 1 | 6 | 7 | 8 | 9;
    MachineRequest: {
      code?: string | null;
      name?: string | null;
      /** Format: uuid */
      workCenterId?: string;
      serialNumber?: string | null;
      isActive?: boolean;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    MachineState: 1 | 2 | 3 | 4 | 5;
    MassLocationTransferCommand: {
      /** Format: uuid */
      targetLocationId?: string;
      /** Format: uuid */
      itemId?: string | null;
      batchNumber?: string | null;
      mrn?: string | null;
      /** Format: uuid */
      sourceWarehouseId?: string | null;
      /** Format: uuid */
      sourceLocationId?: string | null;
      qualityStatus?: components["schemas"]["QualityStatus"];
      lonProcessState?: components["schemas"]["LonProcessState"];
      /** Format: date-time */
      movementDate?: string | null;
      reason?: string | null;
    };
    MassLocationTransferPreviewQuery: {
      /** Format: uuid */
      itemId?: string | null;
      batchNumber?: string | null;
      mrn?: string | null;
      /** Format: uuid */
      sourceWarehouseId?: string | null;
      /** Format: uuid */
      sourceLocationId?: string | null;
      qualityStatus?: components["schemas"]["QualityStatus"];
      lonProcessState?: components["schemas"]["LonProcessState"];
      /** Format: uuid */
      targetLocationId?: string | null;
    };
    MaterialConsumptionDto: {
      /** Format: uuid */
      materialIssueId?: string;
      /** Format: double */
      quantity?: number;
    };
    MaterialIssueLineDto: {
      /** Format: uuid */
      itemId?: string;
      /** Format: double */
      quantity?: number;
      /** Format: uuid */
      uoMId?: string;
      batchNumber?: string | null;
      mrn?: string | null;
      /** Format: uuid */
      locationId?: string | null;
    };
    MoveBatchAcrossStagesCommand: {
      batchNumber?: string | null;
      targetStage?: components["schemas"]["LocationType"];
      /** Format: uuid */
      warehouseId?: string | null;
      /** Format: uuid */
      targetLocationId?: string | null;
      /** Format: date-time */
      movementDate?: string | null;
      reason?: string | null;
    };
    PartnerRequest: {
      code?: string | null;
      name?: string | null;
      partnerType?: components["schemas"]["PartnerType"];
      taxNumber?: string | null;
      vatNumber?: string | null;
      eoriNumber?: string | null;
      address?: string | null;
      city?: string | null;
      postalCode?: string | null;
      country?: string | null;
      contactPerson?: string | null;
      email?: string | null;
      phone?: string | null;
      isActive?: boolean;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    PartnerType: 1 | 2 | 3 | 4 | 5;
    PermissionDto: {
      /** Format: uuid */
      id?: string;
      name?: string | null;
      description?: string | null;
      category?: string | null;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    PickTaskStatus: 1 | 2 | 3 | 4;
    /**
     * Format: int32
     * @enum {integer}
     */
    ProductionOrderStatus: 1 | 2 | 3 | 4 | 5 | 6;
    /**
     * Format: int32
     * @enum {integer}
     */
    QualityStatus: 0 | 1 | 2 | 3;
    QuestionRequest: {
      question?: string | null;
      /** Format: int32 */
      maxContextChunks?: number;
    };
    QuickEntryRequest: {
      command?: string | null;
    };
    RAGResponse: {
      answer?: string | null;
      sources?: components["schemas"]["SourceReference"][] | null;
      errorMessage?: string | null;
      success?: boolean;
    };
    ReceiptLineDto: {
      /** Format: uuid */
      itemId?: string;
      /** Format: double */
      quantity?: number;
      /** Format: uuid */
      uoMId?: string;
      batchNumber?: string | null;
      mrn?: string | null;
      /** Format: uuid */
      locationId?: string | null;
      qualityStatus?: components["schemas"]["QualityStatus"];
      /** Format: date-time */
      expiryDate?: string | null;
      /** Format: uuid */
      customsDeclarationId?: string | null;
    };
    RecordFieldValueRequest: {
      fieldKey?: string | null;
      value?: string | null;
    };
    RefreshTokenRequest: {
      refreshToken?: string | null;
    };
    ReturnLineDto: {
      /** Format: uuid */
      itemId?: string;
      tariffCode?: string | null;
      /** Format: double */
      quantity?: number;
      /** Format: uuid */
      uoMId?: string;
      /** Format: double */
      customsValue?: number;
      countryOfOrigin?: string | null;
      /** Format: double */
      netWeight?: number | null;
      /** Format: double */
      grossWeight?: number | null;
      calculationMethod?: string | null;
      batchNumber?: string | null;
      /** Format: uuid */
      locationId?: string;
      sourceMRN?: string | null;
      /** Format: double */
      returnQuantity?: number;
      returnTo?: components["schemas"]["LonProcessState"];
    };
    RoleDto: {
      /** Format: uuid */
      id?: string;
      name?: string | null;
      description?: string | null;
      isActive?: boolean;
      permissions?: components["schemas"]["PermissionDto"][] | null;
    };
    RoleRequest: {
      name?: string | null;
      description?: string | null;
      permissionIds?: string[] | null;
    };
    RoutingOperationRequest: {
      /** Format: int32 */
      operationNumber?: number;
      /** Format: uuid */
      workCenterId?: string;
      operationName?: string | null;
      /** Format: double */
      standardTime?: number;
      /** Format: double */
      setupTime?: number;
      description?: string | null;
    };
    RoutingRequest: {
      /** Format: uuid */
      itemId?: string;
      version?: string | null;
      description?: string | null;
      isActive?: boolean;
      operations?: components["schemas"]["RoutingOperationRequest"][] | null;
    };
    SearchRequest: {
      query?: string | null;
      /** Format: int32 */
      topK?: number;
      /** Format: double */
      minSimilarity?: number;
      documentType?: string | null;
    };
    SearchResult: {
      /** Format: uuid */
      chunkId?: string;
      /** Format: uuid */
      documentId?: string;
      content?: string | null;
      chunkTitle?: string | null;
      documentTitle?: string | null;
      documentType?: string | null;
      reference?: string | null;
      /** Format: double */
      similarityScore?: number;
    };
    SetDefaultsRequest: {
      defaults?: components["schemas"]["ImportDefaults"];
    };
    SetTransformsRequest: {
      transforms?: components["schemas"]["ImportTransforms"];
    };
    ShiftDto: {
      /** Format: uuid */
      id?: string;
      code?: string | null;
      name?: string | null;
      /** Format: date-span */
      startTime?: string;
      /** Format: date-span */
      endTime?: string;
      description?: string | null;
      isActive?: boolean;
    };
    SourceReference: {
      documentTitle?: string | null;
      reference?: string | null;
      contentSnippet?: string | null;
      /** Format: double */
      relevanceScore?: number;
    };
    Tenant: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      createdAt?: string;
      createdBy?: string | null;
      /** Format: date-time */
      modifiedAt?: string | null;
      modifiedBy?: string | null;
      isDeleted?: boolean;
      domainEvents?: (readonly components["schemas"]["IDomainEvent"][]) | null;
      code?: string | null;
      name?: string | null;
      legacyUvoznik?: string | null;
      taxNumber?: string | null;
      address?: string | null;
      country?: string | null;
      contactName?: string | null;
      email?: string | null;
      phone?: string | null;
      customsAuthorizationNumber?: string | null;
      defaultLanguage?: string | null;
      isActive?: boolean;
      inflateImportForWaste?: boolean;
      allowFefoAutoPick?: boolean;
    };
    TenantFefoFlagRequest: {
      allowFefoAutoPick?: boolean;
    };
    TenantRequest: {
      code?: string | null;
      name?: string | null;
      legacyUvoznik?: string | null;
      taxNumber?: string | null;
      address?: string | null;
      country?: string | null;
      contactName?: string | null;
      email?: string | null;
      phone?: string | null;
      customsAuthorizationNumber?: string | null;
      defaultLanguage?: string | null;
      isActive?: boolean | null;
      inflateImportForWaste?: boolean | null;
      allowFefoAutoPick?: boolean | null;
    };
    UoMRequest: {
      code?: string | null;
      name?: string | null;
      description?: string | null;
      isActive?: boolean | null;
    };
    UpdateCustomsDeclarationCommand: {
      /** Format: uuid */
      id?: string;
      declarationNumber?: string | null;
      /** Format: uuid */
      partnerId?: string | null;
      /** Format: date-time */
      dueDate?: string | null;
      senderName?: string | null;
      senderAddress?: string | null;
      senderCountry?: string | null;
      countryOfDispatch?: string | null;
      countryOfDestination?: string | null;
      specialRemarks?: string | null;
      notes?: string | null;
    };
    UpdateEmployeeRequest: {
      firstName?: string | null;
      lastName?: string | null;
      email?: string | null;
      phone?: string | null;
      position?: string | null;
      department?: string | null;
      isActive?: boolean;
    };
    UpdateScheduleBody: {
      taskDescription?: string | null;
      /** Format: int32 */
      intervalDays?: number;
      /** Format: date-time */
      lastDone?: string | null;
      /** Format: date-time */
      nextDue?: string;
      isActive?: boolean;
    };
    UpdateShiftRequest: {
      name?: string | null;
      startTime?: string | null;
      endTime?: string | null;
      description?: string | null;
      isActive?: boolean;
    };
    UpdateUserRequest: {
      email?: string | null;
      fullName?: string | null;
      isActive?: boolean;
      roleIds?: string[] | null;
    };
    UserDto: {
      /** Format: uuid */
      id?: string;
      username?: string | null;
      email?: string | null;
      isActive?: boolean;
      /** Format: date-time */
      lastLoginAt?: string | null;
      employee?: components["schemas"]["EmployeeDto"];
      roles?: components["schemas"]["RoleDto"][] | null;
      /** Format: date-time */
      createdAt?: string;
    };
    WarehouseRequest: {
      code?: string | null;
      name?: string | null;
      description?: string | null;
      address?: string | null;
      isActive?: boolean;
    };
    WasteSlot: {
      /** Format: int32 */
      slotIndex?: number;
      /** Format: double */
      quantity?: number;
      category?: string | null;
    };
    WorkCenterRequest: {
      code?: string | null;
      name?: string | null;
      description?: string | null;
      isActive?: boolean;
      /** Format: double */
      standardCostPerHour?: number | null;
      /** Format: double */
      capacity?: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
